name: tectojp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  auto_route: ^10.0.1
  google_nav_bar: ^5.0.7
  flutter_localizations:
    sdk: flutter
  intl: any
  shared_preferences: ^2.5.2
  get_it: ^8.0.3
  package_info_plus: ^8.3.0
  dartz: ^0.10.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  auto_route_generator: ^10.0.1
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/quiz/

  fonts:
    - family: Poopins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
    - family: NotoSansJp
      fonts:
        - asset: assets/fonts/notoSansJp/NotoSansJP.ttf
  
